# command-module-index.source.psd1 -- VENDORED source snapshot for the command->module index.
#
# Names-only interoperability metadata (a symbol table): each entry is a command NAME and the
# NAME of the module that exports it. Ships NO module content or code. This is the pinned oracle
# scripts/regen-command-module-index.ps1 derives rulesets/command-module-index.psd1 from (offline);
# its -Check re-derives from THIS file and diffs. Refreshed ONLY by a deliberate dispatch (the
# 000049 .nupkg-vendoring discipline) -- never at edit time, never over the network on the hot path.
#
# source=machine-derived rows were enumerated from a module installed on the build host (real
# provenance). source=curated rows are a documented-public-API subset for high-value modules absent
# on the build host: honest, iconic, unpinned; a refresh dispatch on an installed host pins versions.
#
# Author: Mike Andersen / powershell-lsp plugin (dispatch 000101).

@{
    schema = 'command-module-index-source/v1'
    generated = '2026-07-02'
    modules = @(
        @{
            name = 'ActiveDirectory'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-ADUser'
                'Set-ADUser'
                'New-ADUser'
                'Remove-ADUser'
                'Get-ADGroup'
                'New-ADGroup'
                'Get-ADGroupMember'
                'Add-ADGroupMember'
                'Get-ADComputer'
                'Get-ADDomain'
            )
        }
        @{
            name = 'Az.Accounts'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Connect-AzAccount'
                'Disconnect-AzAccount'
                'Get-AzContext'
                'Set-AzContext'
                'Get-AzSubscription'
                'Get-AzAccessToken'
            )
        }
        @{
            name = 'Az.Compute'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-AzVM'
                'New-AzVM'
                'Start-AzVM'
                'Stop-AzVM'
                'Remove-AzVM'
                'Restart-AzVM'
            )
        }
        @{
            name = 'Az.KeyVault'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-AzKeyVault'
                'Get-AzKeyVaultSecret'
                'Set-AzKeyVaultSecret'
                'Get-AzKeyVaultKey'
            )
        }
        @{
            name = 'Az.Resources'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-AzResource'
                'Get-AzResourceGroup'
                'New-AzResourceGroup'
                'Remove-AzResourceGroup'
                'Get-AzRoleAssignment'
                'New-AzRoleAssignment'
            )
        }
        @{
            name = 'Az.Storage'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-AzStorageAccount'
                'New-AzStorageAccount'
                'Get-AzStorageContainer'
                'New-AzStorageContext'
                'Get-AzStorageBlob'
                'Set-AzStorageBlobContent'
            )
        }
        @{
            name = 'dbatools'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-DbaDatabase'
                'Backup-DbaDatabase'
                'Restore-DbaDatabase'
                'Copy-DbaDatabase'
                'Invoke-DbaQuery'
                'Connect-DbaInstance'
                'Get-DbaAgentJob'
            )
        }
        @{
            name = 'ExchangeOnlineManagement'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Connect-ExchangeOnline'
                'Disconnect-ExchangeOnline'
                'Get-EXOMailbox'
                'Get-EXORecipient'
                'Get-EXOMailboxStatistics'
                'Get-ConnectionInformation'
            )
        }
        @{
            name = 'ImportExcel'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Import-Excel'
                'Export-Excel'
                'Open-ExcelPackage'
                'Close-ExcelPackage'
                'Add-ExcelChart'
                'Set-ExcelRange'
            )
        }
        @{
            name = 'Microsoft.Graph.Authentication'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Connect-MgGraph'
                'Disconnect-MgGraph'
                'Get-MgContext'
                'Invoke-MgGraphRequest'
            )
        }
        @{
            name = 'Microsoft.Graph.Groups'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-MgGroup'
                'New-MgGroup'
                'Update-MgGroup'
                'Remove-MgGroup'
                'Get-MgGroupMember'
            )
        }
        @{
            name = 'Microsoft.Graph.Users'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Get-MgUser'
                'New-MgUser'
                'Update-MgUser'
                'Remove-MgUser'
                'Get-MgUserMessage'
            )
        }
        @{
            name = 'Pester'
            version = '5.7.1'
            source = 'machine-derived'
            provenance = 'Get-Command -Module Pester on the build host (pwsh 7.6.3), 2026-07-02'
            commands = @(
                'Add-ShouldOperator'
                'AfterAll'
                'AfterEach'
                'Assert-MockCalled'
                'Assert-VerifiableMock'
                'BeforeAll'
                'BeforeDiscovery'
                'BeforeEach'
                'Context'
                'ConvertTo-JUnitReport'
                'ConvertTo-NUnitReport'
                'ConvertTo-Pester4Result'
                'Describe'
                'Export-JUnitReport'
                'Export-NUnitReport'
                'Get-ShouldOperator'
                'InModuleScope'
                'Invoke-Pester'
                'It'
                'Mock'
                'New-Fixture'
                'New-MockObject'
                'New-PesterConfiguration'
                'New-PesterContainer'
                'Set-ItResult'
                'Should'
            )
        }
        @{
            name = 'PnP.PowerShell'
            version = ''
            source = 'curated'
            provenance = 'documented public API; iconic high-confidence subset; NOT machine-derived (module absent on build host); refresh + version-pin via a deliberate dispatch on an installed host'
            commands = @(
                'Connect-PnPOnline'
                'Disconnect-PnPOnline'
                'Get-PnPList'
                'Get-PnPListItem'
                'Add-PnPListItem'
                'Get-PnPWeb'
                'Get-PnPSite'
            )
        }
    )
    # rung 1 built-in / default-module denylist: names shipped by PowerShell itself and the
    # always-present modules. A name here is NEVER placed in the index (a built-in always wins).
    builtins = @(
        'Add-Content'
        'Add-History'
        'Add-Member'
        'Add-Type'
        'Clear-Content'
        'Clear-History'
        'Clear-Item'
        'Clear-ItemProperty'
        'Clear-RecycleBin'
        'Clear-Variable'
        'Compare-Object'
        'Connect-PSSession'
        'Connect-WSMan'
        'Convert-Path'
        'ConvertFrom-CliXml'
        'ConvertFrom-Csv'
        'ConvertFrom-Json'
        'ConvertFrom-Markdown'
        'ConvertFrom-SddlString'
        'ConvertFrom-SecureString'
        'ConvertFrom-StringData'
        'ConvertTo-CliXml'
        'ConvertTo-Csv'
        'ConvertTo-Html'
        'ConvertTo-Json'
        'ConvertTo-SecureString'
        'ConvertTo-Xml'
        'Copy-Item'
        'Copy-ItemProperty'
        'Debug-Job'
        'Debug-Process'
        'Debug-Runspace'
        'Disable-ExperimentalFeature'
        'Disable-PSBreakpoint'
        'Disable-PSRemoting'
        'Disable-PSSessionConfiguration'
        'Disable-RunspaceDebug'
        'Disable-WSManCredSSP'
        'Disconnect-PSSession'
        'Disconnect-WSMan'
        'Enable-ExperimentalFeature'
        'Enable-PSBreakpoint'
        'Enable-PSRemoting'
        'Enable-PSSessionConfiguration'
        'Enable-RunspaceDebug'
        'Enable-WSManCredSSP'
        'Enter-PSHostProcess'
        'Enter-PSSession'
        'Exit-PSHostProcess'
        'Exit-PSSession'
        'Export-Alias'
        'Export-Clixml'
        'Export-Csv'
        'Export-FormatData'
        'Export-ModuleMember'
        'Export-PSSession'
        'fhx'
        'fimo'
        'Find-Command'
        'Find-DscResource'
        'Find-Module'
        'Find-Package'
        'Find-PackageProvider'
        'Find-RoleCapability'
        'Find-Script'
        'ForEach-Object'
        'Format-Custom'
        'Format-Hex'
        'Format-List'
        'Format-Table'
        'Format-Wide'
        'gcai'
        'gcb'
        'gcim'
        'gcls'
        'gcms'
        'Get-Acl'
        'Get-Alias'
        'Get-AuthenticodeSignature'
        'Get-ChildItem'
        'Get-CimAssociatedInstance'
        'Get-CimClass'
        'Get-CimInstance'
        'Get-CimSession'
        'Get-Clipboard'
        'Get-CmsMessage'
        'Get-Command'
        'Get-ComputerInfo'
        'Get-Content'
        'Get-Counter'
        'Get-Credential'
        'Get-CredsFromCredentialProvider'
        'Get-Culture'
        'Get-Date'
        'Get-Error'
        'Get-Event'
        'Get-EventSubscriber'
        'Get-ExecutionPolicy'
        'Get-ExperimentalFeature'
        'Get-FileHash'
        'Get-FormatData'
        'Get-Help'
        'Get-History'
        'Get-Host'
        'Get-HotFix'
        'Get-InstalledModule'
        'Get-InstalledScript'
        'Get-Item'
        'Get-ItemProperty'
        'Get-ItemPropertyValue'
        'Get-Job'
        'Get-Location'
        'Get-MarkdownOption'
        'Get-Member'
        'Get-Module'
        'Get-Package'
        'Get-PackageProvider'
        'Get-PackageSource'
        'Get-PfxCertificate'
        'Get-Process'
        'Get-PSBreakpoint'
        'Get-PSCallStack'
        'Get-PSDrive'
        'Get-PSHostProcessInfo'
        'Get-PSProvider'
        'Get-PSReadLineKeyHandler'
        'Get-PSReadLineOption'
        'Get-PSRepository'
        'Get-PSSession'
        'Get-PSSessionCapability'
        'Get-PSSessionConfiguration'
        'Get-PSSubsystem'
        'Get-Random'
        'Get-Runspace'
        'Get-RunspaceDebug'
        'Get-SecureRandom'
        'Get-Service'
        'Get-TimeZone'
        'Get-TraceSource'
        'Get-TypeData'
        'Get-UICulture'
        'Get-Unique'
        'Get-Uptime'
        'Get-Variable'
        'Get-Verb'
        'Get-WinEvent'
        'Get-WSManCredSSP'
        'Get-WSManInstance'
        'gin'
        'Group-Object'
        'gtz'
        'icim'
        'Import-Alias'
        'Import-Clixml'
        'Import-Csv'
        'Import-LocalizedData'
        'Import-Module'
        'Import-PackageProvider'
        'Import-PowerShellDataFile'
        'Import-PSSession'
        'inmo'
        'Install-Module'
        'Install-Package'
        'Install-PackageProvider'
        'Install-Script'
        'Invoke-CimMethod'
        'Invoke-Command'
        'Invoke-Expression'
        'Invoke-History'
        'Invoke-Item'
        'Invoke-RestMethod'
        'Invoke-WebRequest'
        'Invoke-WSManAction'
        'Join-Path'
        'Join-String'
        'Measure-Command'
        'Measure-Object'
        'Move-Item'
        'Move-ItemProperty'
        'ncim'
        'ncms'
        'ncso'
        'New-Alias'
        'New-CimInstance'
        'New-CimSession'
        'New-CimSessionOption'
        'New-Event'
        'New-FileCatalog'
        'New-Guid'
        'New-Item'
        'New-ItemProperty'
        'New-Module'
        'New-ModuleManifest'
        'New-Object'
        'New-PSDrive'
        'New-PSRoleCapabilityFile'
        'New-PSSession'
        'New-PSSessionConfigurationFile'
        'New-PSSessionOption'
        'New-PSTransportOption'
        'New-ScriptFileInfo'
        'New-Service'
        'New-TemporaryFile'
        'New-TimeSpan'
        'New-Variable'
        'New-WinEvent'
        'New-WSManInstance'
        'New-WSManSessionOption'
        'Out-Default'
        'Out-File'
        'Out-GridView'
        'Out-Host'
        'Out-Null'
        'Out-Printer'
        'Out-String'
        'Pop-Location'
        'Protect-CmsMessage'
        'PSConsoleHostReadLine'
        'Publish-Module'
        'Publish-Script'
        'pumo'
        'Push-Location'
        'rcie'
        'rcim'
        'rcms'
        'Read-Host'
        'Receive-Job'
        'Receive-PSSession'
        'Register-ArgumentCompleter'
        'Register-CimIndicationEvent'
        'Register-EngineEvent'
        'Register-ObjectEvent'
        'Register-PackageSource'
        'Register-PSRepository'
        'Register-PSSessionConfiguration'
        'Remove-Alias'
        'Remove-CimInstance'
        'Remove-CimSession'
        'Remove-Event'
        'Remove-Item'
        'Remove-ItemProperty'
        'Remove-Job'
        'Remove-Module'
        'Remove-PSBreakpoint'
        'Remove-PSDrive'
        'Remove-PSReadLineKeyHandler'
        'Remove-PSSession'
        'Remove-Service'
        'Remove-TypeData'
        'Remove-Variable'
        'Remove-WSManInstance'
        'Rename-Computer'
        'Rename-Item'
        'Rename-ItemProperty'
        'Resolve-Path'
        'Restart-Computer'
        'Restart-Service'
        'Resume-Service'
        'Save-Help'
        'Save-Module'
        'Save-Package'
        'Save-Script'
        'scb'
        'scim'
        'Select-Object'
        'Select-String'
        'Select-Xml'
        'Send-MailMessage'
        'Set-Acl'
        'Set-Alias'
        'Set-AuthenticodeSignature'
        'Set-CimInstance'
        'Set-Clipboard'
        'Set-Content'
        'Set-Date'
        'Set-ExecutionPolicy'
        'Set-Item'
        'Set-ItemProperty'
        'Set-Location'
        'Set-MarkdownOption'
        'Set-PackageSource'
        'Set-PSBreakpoint'
        'Set-PSDebug'
        'Set-PSReadLineKeyHandler'
        'Set-PSReadLineOption'
        'Set-PSRepository'
        'Set-PSSessionConfiguration'
        'Set-Service'
        'Set-StrictMode'
        'Set-TimeZone'
        'Set-TraceSource'
        'Set-Variable'
        'Set-WSManInstance'
        'Set-WSManQuickConfig'
        'Show-Command'
        'Show-Markdown'
        'Sort-Object'
        'Split-Path'
        'Start-Job'
        'Start-Process'
        'Start-Service'
        'Start-Sleep'
        'Start-Transcript'
        'Stop-Computer'
        'Stop-Job'
        'Stop-Process'
        'Stop-Service'
        'Stop-Transcript'
        'stz'
        'Suspend-Service'
        'Tee-Object'
        'Test-Connection'
        'Test-FileCatalog'
        'Test-Json'
        'Test-ModuleManifest'
        'Test-Path'
        'Test-PSSessionConfigurationFile'
        'Test-ScriptFileInfo'
        'Test-WSMan'
        'Trace-Command'
        'Unblock-File'
        'Uninstall-Module'
        'Uninstall-Package'
        'Uninstall-Script'
        'Unprotect-CmsMessage'
        'Unregister-Event'
        'Unregister-PackageSource'
        'Unregister-PSRepository'
        'Unregister-PSSessionConfiguration'
        'Update-FormatData'
        'Update-Help'
        'Update-List'
        'Update-Module'
        'Update-ModuleManifest'
        'Update-Script'
        'Update-ScriptFileInfo'
        'Update-TypeData'
        'upmo'
        'Wait-Debugger'
        'Wait-Event'
        'Wait-Job'
        'Wait-Process'
        'Where-Object'
        'Write-Debug'
        'Write-Error'
        'Write-Host'
        'Write-Information'
        'Write-Output'
        'Write-Progress'
        'Write-Verbose'
        'Write-Warning'
    )
}
