#Requires -Version 5.1

# regen-surface-history.ps1 -- GENERATE rulesets/surface-history.psd1 (dispatch 000171 leg 4).
#
# THE PROBLEM IT EXISTS FOR. scripts/rule-efficacy-ledger.ps1 unions every per-version capture log
# it finds, deliberately, so a plugin upgrade does not reset the denominator. The consequence
# dispatch 000170 found: the union permanently includes occurrences produced by rules that no
# longer ship, and NO field in the capture record distinguishes them. 000170 had to attribute 65
# of its occurrences by hand-matching message prose.
#
# THE RULING (Mike Andersen, pre-made): do NOT filter the union, and do NOT only tag records
# written from now on. Filtering discards history; tagging forward leaves every pre-change record
# permanently unattributable, which is exactly the state that forced the hand-matching. Instead
# DERIVE the attribution at READ time -- captures already sit in a per-VERSION cache partition, and
# rulesets/base.psd1 is generated and tagged, so the surface at any past version is recoverable.
#
# WHY A COMMITTED FILE RATHER THAN LIVE GIT (open question 3, fork b). The ledger runs from the
# marketplace CACHE, not from a checkout -- there is no repository to query at read time, and a
# reader that shells out to git would silently degrade to "no attribution" for every real user.
# This script does the git work ONCE, at authoring time, and commits the answer.
#
# READ-ONLY over git; writes exactly one file. ASCII-only.
#
# Usage:  pwsh -File scripts/regen-surface-history.ps1
#         pwsh -File scripts/regen-surface-history.ps1 -WhatIf
#
# Author: Mike Andersen / powershell-lsp plugin.

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string] $OutFile = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($OutFile)) { $OutFile = Join-Path $repoRoot 'rulesets/surface-history.psd1' }

# Every rule name in a base.psd1 blob. The character class INCLUDES DIGITS deliberately:
# PSUseUTF8EncodingForHelpFile carries an '8', and a [A-Za-z]-only class silently drops it and
# undercounts the surface by one. That exact miscount was caught during 000171 leg 4 by
# cross-checking a derived count against the decision ledger's recorded 53.
function Get-RuleNamesFromPsd1Text {
    param([string] $Text)
    return @([regex]::Matches($Text, "(?m)^\s*'(P[A-Za-z0-9]+)'") | ForEach-Object { $_.Groups[1].Value })
}

$tags = @(& git -C $repoRoot tag --list 'v*' | Where-Object { $_ -match '^v\d+\.\d+\.\d+$' })
if ($tags.Count -eq 0) { throw 'no release tags found; cannot build a surface history.' }

$rows = New-Object System.Collections.Generic.List[object]
foreach ($tag in @($tags | Sort-Object { [version]($_.Substring(1)) })) {
    $blob = ''
    try { $blob = (& git -C $repoRoot show ($tag + ':rulesets/base.psd1') 2>$null) -join "`n" } catch { $blob = '' }
    if ([string]::IsNullOrWhiteSpace($blob)) {
        # A tag predating rulesets/base.psd1 has NO base surface. Recorded explicitly as an empty
        # set rather than skipped, so a reader can tell "no base ruleset at this version" from
        # "this version is unknown to the history".
        $rows.Add([pscustomobject]@{ Version = $tag.Substring(1); Rules = @(); HasBase = $false }) | Out-Null
        continue
    }
    $rows.Add([pscustomobject]@{ Version = $tag.Substring(1); Rules = @(Get-RuleNamesFromPsd1Text $blob | Sort-Object); HasBase = $true }) | Out-Null
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# surface-history.psd1 -- GENERATED by scripts/regen-surface-history.ps1. DO NOT EDIT BY HAND.')
[void]$sb.AppendLine('#')
[void]$sb.AppendLine('# Maps each released plugin VERSION to the `base` rule surface that shipped at that version,')
[void]$sb.AppendLine('# so scripts/rule-efficacy-ledger.ps1 can attribute a historical capture to the surface that')
[void]$sb.AppendLine('# was live when it was captured -- WITHOUT needing git at read time (the ledger runs from the')
[void]$sb.AppendLine('# marketplace cache, where no repository exists).')
[void]$sb.AppendLine('#')
[void]$sb.AppendLine('# KNOWN LIMIT, stated because it is load-bearing: this records the PSScriptAnalyzer rule')
[void]$sb.AppendLine('# surface only. It does NOT record the internal RUNGS of the plugin''s own owned finders')
[void]$sb.AppendLine('# (ManifestConsistency and friends). A finder whose rule id still ships but one of whose rungs')
[void]$sb.AppendLine('# was removed -- which is precisely the 000162 under-declared-export case behind 65 of the')
[void]$sb.AppendLine('# occurrences 000170 had to hand-attribute -- is NOT distinguishable from this table alone.')
[void]$sb.AppendLine('@{')
[void]$sb.AppendLine('    versions = @(')
foreach ($r in $rows) {
    [void]$sb.AppendLine('        @{')
    [void]$sb.AppendLine(("            version = '" + $r.Version + "'"))
    [void]$sb.AppendLine(("            hasBase = `$" + ([string]$r.HasBase).ToLowerInvariant()))
    if (@($r.Rules).Count -eq 0) {
        [void]$sb.AppendLine('            rules = @()')
    } else {
        [void]$sb.AppendLine('            rules = @(')
        foreach ($n in @($r.Rules)) { [void]$sb.AppendLine(("                '" + $n + "'")) }
        [void]$sb.AppendLine('            )')
    }
    [void]$sb.AppendLine('        }')
}
[void]$sb.AppendLine('    )')
[void]$sb.AppendLine('}')

if ($PSCmdlet.ShouldProcess($OutFile, 'write surface history')) {
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($OutFile, $sb.ToString(), $enc)
    Write-Host ('wrote ' + $OutFile + ' -- ' + $rows.Count + ' versions')
    foreach ($r in $rows) { Write-Host ('   ' + $r.Version.PadRight(10) + @($r.Rules).Count + ' base rules') }
} else {
    Write-Host ('WhatIf: would write ' + $OutFile + ' -- ' + $rows.Count + ' versions')
}
